---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-node-{{ checksum "package-lock.json" }}
            - v2-node-
      - run:
          name: install node dependencies
          command: npm install
      - save_cache:
          key: v2-node-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - restore_cache:
          keys:
            - v1-ruby-{{ checksum "Gemfile.lock" }}
            - v1-ruby-
      - run:
          name: install ruby dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-ruby-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test

  qa:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-{{ checksum "package-lock.json" }}
            - v2-node-
      - restore_cache:
          keys:
            - v1-ruby-{{ checksum "Gemfile.lock" }}
            - v1-ruby-
      - run:
          name: install node dependencies
          command: npm install
      - run:
          name: install ruby dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: build
          command: npm run build
      - run:
          name: qa
          command: npm run qa


workflows:
  version: 2
  commit:
    jobs:
      - build

  weekly:
    jobs:
      - qa
    triggers:
      - schedule:
          cron: "0 15 * * 1"
          filters:
            branches:
              only:
                - main
